services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
    networks:
      - aqbank-network

  php:
    build:
      context: ./php
    volumes:
      - ./:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CLIENT_HOST: host.docker.internal
    depends_on:
      - mysql
    networks:
      - aqbank-network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    ports:
        - "3306:3306"
    networks:
      - aqbank-network

networks:
    aqbank-network:
        driver: bridge
